### ISSUE TITLE
ghc-9.8.1 build failure

### ISSUE THREAD

**Issue by shayne-fletcher** [alanz/ghc-exactprint#131]
ghc-exactprint-1.7.0.1 fails to build with ghc-9.8.1. need to admit base == 4.19. then there are some compile failures indicating updates to the ghc-9.8 api are needed.

**Comment by pranaysashank** [comment]
@alanz can we get a release on hackage supporting ghc 9.8, it looks like you already have a ready to go implementation on `ghc-9.8` branch (I ran it locally and all the tests are passing as well). This will unblock downstream packages waiting for the release

**Comment by alanz** [comment]
Yes.  I did not do it before as it needed head.hackage and allow-newer.

**Comment by alanz** [comment]
https://github.com/alanz/ghc-exactprint/pull/134

**Comment by alanz** [comment]
https://hackage.haskell.org/package/ghc-exactprint-1.8.0.0
