### ISSUE TITLE
Add default annotations for pretty printing

### ISSUE THREAD

**Issue by alanz** [alanz/ghc-exactprint#37]
When a raw AST fragment is provided without annotations, print it so that it is sane and visible.

**Comment by gridaphobe** [comment]
I'd be willing to take a crack at this if you can provide some pointers on where to start. I was just looking at `printStringAtMaybeAnnThen`, but it appears that's too late in the pipeline.

**Comment by alanz** [comment]
I think in the `Language.Haskell.GHC.ExactPrint.Print` module would need modification so that if it looks up an annotation and it is not there it uses an alternate default version.

The problem is that a lot of annotations are optional as a given datatype can appear in multiple roles in the AST, so simply doing a default on every possible annotation via a separate lookup would not work. There would have to be a degree of context awareness.

So running a separate pass on the unannotated AST to add the appropriate defaults might be a simpler process, which would then be another interpreter over AnnotationF, doing something similar to the `Delta` one but using built-in knowledge to use defaults.

Or, as @mpickering suggested, the simplest might be to just use the GHC pretty-printer, and then parse it using ghc-exactprint to get a fully annotated AST which can be spliced into the original.  Of course there is still an open ticket on GHC (https://ghc.haskell.org/trac/ghc/ticket/3384)  to verify that the output of the GHC pretty-printer is in fact a faithful representation of the original.  i.e. that parsing the pretty-printer output yields the same AST.

This is just an initial brain dump, sorry if it is a bit incoherent.

**Comment by alanz** [comment]
This feature exists in current master, via `addAnnotationsForPretty`
