### ISSUE TITLE
Tests fail on file that's on hackage but not git

### ISSUE THREAD

**Issue by mdorman** [alanz/ghc-exactprint#43]
Trying to build `ghc-exactprint` on `NixOS`, I see:
```
GHC8
### Error in:   1:Round-trip tests:0:ghc710:104
parse error on input ‘]’tests/examples/ghc710/OldQuasiQuote.hs
CallStack (from HasCallStack):
  error, called at tests/Test.hs:130:54 in main:Main
Cases: 858  Tried: 858  Errors: 1  Failures: 0
Counts {cases = 858, tried = 858, errors = 1, failures = 0}
Test suite test: FAIL
Test suite logged to: dist/test/ghc-exactprint-0.5.2-test.log
0 of 1 test suites (0 of 1 test cases) passed.
```
The strange thing is, while that file does exist in the distribution ([as you can see here](https://hackage.haskell.org/package/ghc-exactprint-0.5.2/src/tests/examples/ghc710/OldQuasiQuote.hs), it doesn't exist in git.  I'm betting it was a file renamed out of the way during development that got picked up when creating the source distribution.  Regardless, might be good to drop a 0.5.2.1 release without it.

**Comment by mpickering** [comment]
Thanks Michael, it should be fixed now.
