### ISSUE TITLE
delta in unexpected places

### ISSUE THREAD

**Issue by xich** [alanz/ghc-exactprint#45]
If I parse and dump the annotations for `print $ 3 + 4`, I get:

```
AnnKey debug:1:1-5 CN "HsVar"
  (Ann (DP (0,0)) [] [] [((G AnnVal),DP (0,0))] Nothing Nothing)
AnnKey debug:1:1-9 CN "OpApp"
  (Ann (DP (0,0)) [] [] [] Nothing Nothing)
AnnKey debug:1:1-13 CN "OpApp"
  (Ann (DP (0,0)) [] [] [] Nothing Nothing)
AnnKey debug:1:7 CN "HsVar"
  (Ann (DP (0,1)) [] [] [((G AnnVal),DP (0,0))] Nothing Nothing)
AnnKey debug:1:9 CN "HsOverLit"
  (Ann (DP (0,1)) [] [] [((G AnnVal),DP (0,0))] Nothing Nothing)
AnnKey debug:1:11 CN "HsVar"
  (Ann (DP (0,1)) [] [] [((G AnnVal),DP (0,0))] Nothing Nothing)
AnnKey debug:1:13 CN "HsOverLit"
  (Ann (DP (0,1)) [] [] [((G AnnVal),DP (0,0))] Nothing Nothing)
```

The delta offset for `3 + 4` is actually on `3`, instead of `+`, as I would've guessed. This makes it difficult to transfer/swap deltas correctly. If I try to set the delta entry of `3 + 4`, I get the extra space from `3`.

Are there library functions I've missed for getting/setting the "true" offset of an expression like `3 + 4`? (Perhaps by walking the left children... for whatever "left" means.) Alternatively, is it possible to assign the delta entry to `+` instead of `3`? (And in general, assign to the outermost enclosing AST element.)

**Comment by mpickering** [comment]
Are you not actually expecting the +1 to be on the `OpApp` rather than the `HsVar`?

**Comment by xich** [comment]
I've just realized this is because of the left-associated parsing of operators. :-P

Putting the offset on `3` is the only thing it can do, because it thinks `3` is the right child of `$`.

**Comment by mpickering** [comment]
There is some code in `apply-refact` which applies fixity information to the tree and rearranges the deltas. Might that be of use to you?

**Comment by xich** [comment]
Ah it probably would've been. I just finished doing that myself. (And came up with largely the same solution.)

**Comment by alanz** [comment]
PR welcomed ....
