### ISSUE TITLE
GHC 8.6 compatibility?

### ISSUE THREAD

**Issue by ulysses4ever** [alanz/ghc-exactprint#69]
I have
```
$ cabal --version
cabal-install version 2.2.0.0
compiled using version 2.2.0.1 of the Cabal library 
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.0.20180907

```
(courtesy HVR's PPA)
When cloning the source and doing `cabal new-build` I get
```
src/Language/Haskell/GHC/ExactPrint/Parsers.hs:305:3: error:
    • Could not deduce (Control.Monad.Fail.MonadFail m)
        arising from a do statement
        with the failable pattern ‘(dflags3, [], [])’
...
```
Am I doing something wrong?

**Comment by alanz** [comment]
Nope.  It is compatible with the prior beta (alpha?) of GHC 8.6, when the beta landed it had the monad fail proposal enabled, and it broke again.

I have not managed to fix it yet, there are a bunch of changes needed in ghc-mod first.

**Comment by qrilka** [comment]
@alanz isn't it fixed already?

**Comment by ulysses4ever** [comment]
Indeed, it works for me now. Thanks, @qrilka!
