### ISSUE TITLE
Release 0.6.3.3

### ISSUE THREAD

**Issue by zliu41** [alanz/ghc-exactprint#95]
@alanz Do you mind making a release? I think multiple users have reported the bug in #92 which was fixed in #94 so it's probably worth making a release for it.

**Comment by alanz** [comment]
Sorry, will do so later today when I am able to

**Comment by zliu41** [comment]
Thanks!

**Comment by alanz** [comment]
Released  http://hackage.haskell.org/package/ghc-exactprint-0.6.3.3
